### ISSUE TITLE
Ability to add comments to batch file

### ISSUE THREAD

**Issue by benbarclay** [Deathspike/mangarack.js#20]
Unless I am missing something, there is currently no way to comment out a line in the batch file.

This would be handy for all sorts of things. 

Two that immediately come to mind are:
1. Commenting out entries that are currently broken on KissManga
2. Adding heading sections to group the links (currently reading, plan to read, etc)

**Comment by benbarclay** [comment]
Although messing up URL's by starting with an invalid character solves #1 and #2 pretty much works already. So I might just close this.

**Comment by Deathspike** [comment]
It's a good enhancement; no need to close the request ;-)

It's also a simple one that is easily integrated. I'm thinking of `#` as prefix. Any preference?

**Comment by XellossMetallium** [comment]
Indeed, until now I just added a ; at the start of the lines I wanted to exclude (quite a lot since I wanted to leave the url of completed series without aggravating too much the scanning operation). The effect was "Obscured" when executing the batch.
 
So this feature would directly skip the line without any notice in the cmd window itself? Nice!

**Comment by benbarclay** [comment]
My preference would be for ```//``` (for JS style) or for ```#``` (bash style).

**Comment by Deathspike** [comment]
Both are allowed. Whatever floats your boat. Available in next patch!
