### ISSUE TITLE
Question about switches

### ISSUE THREAD

**Issue by damidget** [Deathspike/mangarack.js#23]
I've been trying to get all the different switches to work in my MangaRack.txt file...
How do I utilise the --source command for a file called ```MangaList.txt```?
I've tried ```-s E:\Manga\MangaList.txt```  ```-s MangaList.txt```

Do I need to put the output in front of EACH URL for EACH Manga series?
ie.
```
--output E:\Manga URL
--output E:\Manga URL
--output E:\Manga URL
. . . etc
```
or can I state the address for all URL's in a text file so i don't have to repeat the directory each time?
ie.
```
--output E:\Manga
URL
URL
. . . etc
```
is there anywhere I can go to learn this stuff by myself? Any help in this is greatly appreciated, I've got a big library and I'm considering splitting it up across multiple directories.

**Comment by XellossMetallium** [comment]
Hi, I learned by trying too. You can add the switch at the start of each url, but this is useful only for certian switches (i.e. start by chapter/volume).
It's easier to add the switches to the bat file which starts the operation. This can be done in "cascade".

In my case I have a bat file which check for updates and then starts other batches for each alphabet letter. 
Like this:
call npm update -g mangarack
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\Download#.bat
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\Download~KissManga.bat
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\Download~MangaFox.bat
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\Download~Manhwa.bat
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\DownloadA.bat
call H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\DownloadB.bat

These batches are like this:

call %AppData%\npm\mangarack --generalize --source H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\-\Liste\A.txt --output H:\#ARCHIVIO\BIBLIOTECA\MANGA\#MANGA\A

each list (by letter) is like:

//ONGOING
url1
-chapter xx url2
url3
//COMPLETE
#url4


This way I have different folders for each letter, I'm able to update only a certian list and to keep things separate and clean.
I'm sure there would be better ways to do it, but these are my two cents. Hope it can help :)

**Comment by Deathspike** [comment]
I believe that you are using the Windows `.bat` helper file. Open it and you will see the following line:

    call %AppData%\npm\mangarack

This means that MangaRack runs without arguments, and thus uses a source file for batch-mode. Each line in the source file is handled as if it was a command line argument, which is why you can use switches on each line (e.g. `-v 2 http://...`). But, the line from the file is actually executed as a joined line of the *real* command line arguments and the ones from the file. Imagine you have this in your `.bat` file:

    call %AppData%\npm\mangarack --output F:\Manga

And this in your batch file:

    -c 100 http://mangafox.me/manga/fairy_tail/
    -c 150 http://mangafox.me/manga/skip_beat/

Then this is executed as:

    --output F:\Manga -c 100 http://mangafox.me/manga/fairy_tail/
    --output F:\Manga -c 150 http://mangafox.me/manga/skip_beat/

You can see that the arguments from the `.bat` file are prepended to each line from the source file. So if you want to affect everything in your source file, that's the way to go. Then, as @XellossMetallium mentioned, you can also chain multiple mangarack invocations for different settings with different batch files.

Very powerful stuff right there. Does this help you? :-)

**Comment by Deathspike** [comment]
Closing this for now. Feel free to open if there are further questions.
